### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Yaffle** [vukicevic/crunch#11]
Hello, I am creating a benchmark for arbitrary-precision integer libs in js, I have found some issues with your lib:

`crunch.parse("-256")` gives `[1, 0]`, not `[-1, 0]` - how to parse negative numbers?

`crunch.mod([-4], [3])` gives `[-4]`, not `[-1]`

`crunch.leftShift([-3], 8)` gives `[3, 0]`, not `[-3, 0]`
`crunch.rightShift([-3], 8)` gives `[0]`, not `[-1]`
`crunch.leftShift([1, 0, 0, 0, 0], 1)` gives `[0]`, not `[2, 0, 0, 0, 0]`
Seems next change should fix this 
```
// https://github.com/vukicevic/crunch/blob/master/crunch.js#L979
-      return transformOut(lsh(transformIn([x]), s));
+      return transformOut(lsh(transformIn([x])[0], s));
// https://github.com/vukicevic/crunch/blob/master/crunch.js#L991
-      return transformOut(rsh(transformIn([x]), s));
+      return transformOut(rsh(transformIn([x])[0], s));
```

**Comment by vukicevic** [comment]
Firstly, thanks for opening the issue, much appreciated.

`crunch.leftShift([1, 0, 0, 0, 0], 1)` has been fixed, there was a code bug affecting leftShift and rightShift, any number larger than 28 bits was affected.

`crunch.leftShift([-3], 8)` has been fixed as well, the sign will be retained.

`crunch.mod([-4], [3])` there was a bug here, negative numbers were not calculated properly. Having said that, you expect [-1] whereas the result should always be positive as far as I know ([2] in this case). So please check that.

Regarding `crunch.rightShift([-3], 8)`, right shift is defined in the readme as unsigned right shift (>>>), although it doesn't actually perform that way either ... crunch uses a form of signed-magnitude representation rather than two's complement representation for negative numbers, so right shifting will not produce the same result as when it is done to complement representation. In this case the answer should be 0, albeit -0. I'll try to document this in a better way.

All this is currently in the i11 branch and will be merged soon, I'll create a fresh release once all test are passing.

**Comment by Yaffle** [comment]
@vukicevic , thanks for fixing this
one more issue:
`crunch.div([-10], [10])` gives `[-0]`, seems, because at https://github.com/vukicevic/crunch/blob/master/crunch.js#L348 `u` and `v` can be `negative`, i tried with `u.negative = false; v.negative = false;` and got `[-1]`.

`crunch.mod([-4], [3])` gives `[2]` now
Your mod result is always positive and division is a truncated division, so the quotient q and the remainder r of a divided by n do not satisfy `a = nq + r`.
see http://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation .
In JavaScript `-4 % 3 == -1` (as with truncated division).
Possibly, behaviour of your `div` and `mod` is good, so you can ignore this issue.

`crunch.rightShift([-3], 8)`:
Actually, most of other "biginteger" libs do not implement ">>>", and instead implement only ">>", trying to match the behaviour of two's complement represenation: `x >> y` ~ `floor(x / 2**y)`

**Comment by vukicevic** [comment]
You have a point, following the JavaScript convention for mod does seem logical. I'll make the change, it's trivial.

I'm not yet sure about rightShift, it would require making it simulate two's complement while the number itself is not in two's complement. For example -5287 is represented with [-20, 167], but a two's complement representation would be [-21, 89]. I may implement another rightShiftTwosComplement or something similar to produce the desired result.

**Comment by Yaffle** [comment]
@vukicevic , seems, right shift `x >> y` is equivalent to `floor(x / 2**y)`, so you could do then shift and subtract `1` from the result in case some non-zero bit was "removed".
